name: Gitslice CI

on:
  workflow_dispatch:
    inputs:
      clientCommitMessage:
        description: 'Commit message'
        required: true
      branch:
        description: 'Branch to push'
        required: true
      forcePush:
        description: 'Force push branch ?'
        default: 'true'
        required: false

env:
  GIT_SLICE_DEFAULT_BRANCH: main

jobs:
  gitslice-pull:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16.0]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: 'CoherentCapital/tms-flexcel-optimisation'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install GitSlice and setup Bot
        run: |
          npm install -g https://github.com/GitStartHQ/git-slice.git#ignore_dir
          #git config --global user.email ${{ secrets.EMAIL }}
          #git config --global user.name ${{ secrets.USERNAME }}
      - name: Gitslice pull
        run: |
          git fetch -f
