name: rebase-test
on:
  issue_comment:
    types: [created]

jobs:
  try_comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_TOKEN || github.token }}
          fetch-depth: 0

      - name: rebase
        uses: MobileheadHolding/github-action-rebase@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
