name: rebase-test
on:
 pull_request_target:
  types:[labeled]

jobs:
  try_comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - uses: actions/checkout@v2
        with:
          token:${{ secrets.GITSTART_BOT_TOKEN }}
          fetch-depth: 1

      - name: rebase
        uses: MobileheadHolding/github-action-rebase@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
