name: rebase-test
on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: 'Commit message for the client?'
        required: true
      overide:
        description: 'Overide pervious push (force push)? (false/true)'
        default: 'false'
        required: false
      branch:
        description: 'Which branch should be pushed to the client?'
        required: true
      pushPr:
        description: 'Create a PR with the same title and body on the client side? (false/true)'
        required: false
jobs:
  try_comment:
    runs-on: ubuntu-latest
    #if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: rebase
        uses: MobileheadHolding/github-action-rebase@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
