name: rebase-test
on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: 'Commit message for the client?'
        required: true
      branch:
        description: 'Which branch should be pushed to the client?'
        required: true
jobs:
  try_comment:
    runs-on: ubuntu-latest
    #if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref || github.ref }}
          repository: 'CoherentCapital/tms-flexcel-optimisation'
          fetch-depth: 0

      - name: rebase
        uses: MobileheadHolding/github-action-rebase@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
